### PR TITLE
added clearable option to date picker

### PR DESCRIPTION
**Pull request by kialj876**
Signed-off-by: Kial Jinnah <kialj876@gmail.com>

*Issue #:* /bcgov/entity#10146

*Description of changes:*
- clearable option added

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — APPROVED** [review]
LGTM

**Review by argush3 — APPROVED** [review]
approved assuming merge conflicts are resolved before merging.

**Review by cameron-freshworks — APPROVED** [review]
Looks good!

**Comment by cameron-freshworks** [comment]
There was a recent commit here that might have caused the conflict. 
Perhaps rebase main, try a rebuild and commit that. 🤞  Hopefully that resolves the conflict!

**Comment by kialj876** [comment]
> There was a recent commit here that might have caused the conflict. Perhaps rebase main, try a rebuild and commit that. 🤞 Hopefully that resolves the conflict!

ah yeah I just did it through the UI since it was super tiny

**Comment by cameron-freshworks** [comment]
> > There was a recent commit here that might have caused the conflict. Perhaps rebase main, try a rebuild and commit that. 🤞 Hopefully that resolves the conflict!
> 
> ah yeah I just did it through the UI since it was super tiny

No prob, sounds good!

**Comment by kialj876** [comment]
> > > There was a recent commit here that might have caused the conflict. Perhaps rebase main, try a rebuild and commit that. 🤞 Hopefully that resolves the conflict!
> > 
> > 
> > ah yeah I just did it through the UI since it was super tiny
> 
> No prob, sounds good!

Oh now it actually shows all the other changes from that in my diff :(

next time I won't do that!

**Pull request merged**
